version: '3.4'

services:
  pythoncopy:
    image: pythoncopy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 CUAHANGTRANGSUC/Cuahangtrangsuc/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 5678:5678
